name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      LIFFID: ${{ secrets.LIFFID }} 
      GAS_URL: ${{ secrets.GAS_URL }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git

      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Download Flutter packages
        run: flutter pub get

      - name: Create .env
        run: |
          touch .env
          echo $LIFFID >> .env
          echo $GAS_URL >> .env

      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_LIFF_SCHEDULER }}'
          channelId: live
          projectId: flutter-liff-scheduler
